### PR TITLE
Goschiea boards ui

### PR DESCRIPTION
**Pull request by agoschie**
Completes Issue #27 #29 #30 #33

### CODE REVIEW

**Comment by radiian** [comment]
The code looks solid. My only complaint is a few inconsistencies in the indentation of the CSS and one or two JS files. I suggest attempting to resolve the Travis CI issues before the merge though.

**Comment by Simouie** [comment]
I did not see any issues with the code. The HTML and CSS is somewhat messy, but it is a style issue. Refactoring may be a good idea, if time allows. 

There are some things that will need to be discussed by team. In the UI design, the counters on the side were supposed to track the number of remaining ships, not number of ships sunk. The coordinates were not part of the UI design, and are not used in gameplay.

**Comment by radiian** [comment]
+1 approval for this merge

**Comment by agoschie** [comment]
> I did not see any issues with the code. The HTML and CSS is somewhat messy, but it is a style issue. Refactoring may be a good idea, if time allows.
> 
> There are some things that will need to be discussed by team. In the final UI design, the counters on the side were supposed to track the number of remaining ships, not number of ships sunk. The coordinates were not part of the final UI design, and are not actually used in gameplay. We could alter our design, of course, but it should involve some discussion.

I changed the boards to use a placed ships counter instead. Thanks for catching this.

**Pull request merged**
